[package]
name = "paperclips"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
eframe = "0.33.0"
egui_extras = "0.33.0"
rand = "0.9.2"
strum = { version = "0.27.2", features = ["derive"] }
